Try to loop over interfaces twice
```
error[E0502]: cannot borrow `*interfaces` as immutable because it is also borrowed as mutable
  --> agama-migrate-wicked/src/reader.rs:28:22
   |
25 |     for i in interfaces.iter_mut() {
   |              ---------------------
   |              |
   |              mutable borrow occurs here
   |              mutable borrow later used here
...
28 |             for j in interfaces.iter() {
   |                      ^^^^^^^^^^^^^^^^^ immutable borrow occurs here
```